language: php

sudo: false

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_install:
  - composer self-update

install:
  - composer update

script:
  - vendor/bin/phpunit

cache:
  directories:
    - $HOME/.composer/cache
